Tue, 29 Nov 2022 18:57:43 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'172.30.0.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:11:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Tue, 29 Nov 2022 18:58:56 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'172.30.0.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:11:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Thu, 01 Dec 2022 10:22:44 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'192.168.16.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:11:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Thu, 01 Dec 2022 10:22:53 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'192.168.16.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:11:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Thu, 01 Dec 2022 10:23:14 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'192.168.16.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:64:29)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Thu, 01 Dec 2022 10:23:17 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'192.168.16.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:64:29)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Thu, 01 Dec 2022 10:23:47 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'192.168.16.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:17:29)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Thu, 01 Dec 2022 10:23:51 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'192.168.16.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:17:29)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Thu, 01 Dec 2022 10:53:40 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'192.168.16.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:12:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Thu, 01 Dec 2022 10:53:44 GMT
catchAll error
Stack: Error: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'192.168.16.1' (using password: NO)
    at Handshake.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Handshake.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Handshake.js:123:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:17:29)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 07:03:49 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'daniel' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:57:29)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 07:13:21 GMT
catchAll error
Stack: Error: ER_NO_SUCH_TABLE: Table 'vacations.userss' doesn't exist
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:58:29)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 08:03:14 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:95:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 08:03:55 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:95:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 08:04:01 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:95:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 08:04:38 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:95:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 08:04:38 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:95:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 08:04:46 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:95:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 08:05:02 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:95:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 08:05:50 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:95:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 08:05:54 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:95:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 04 Dec 2022 16:46:47 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:96:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 18:53:04 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'WHERE vacationId = 6 AND id = 36' at line 1
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:107:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 18:56:10 GMT
catchAll error
Stack: Error: ER_NO_REFERENCED_ROW_2: Cannot add or update a child row: a foreign key constraint fails (`vacations`.`followers`, CONSTRAINT `followers_ibfk_1` FOREIGN KEY (`userId`) REFERENCES `users` (`id`) ON DELETE CASCADE ON UPDATE CASCADE)
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:110:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 19:22:44 GMT
catchAll error
Stack: Error: ER_BAD_NULL_ERROR: Column 'imageName' cannot be null
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:39:38)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 19:22:55 GMT
catchAll error
Stack: Error: ER_BAD_NULL_ERROR: Column 'imageName' cannot be null
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:39:38)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 19:34:24 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:124:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 19:36:03 GMT
catchAll error
Stack: Error: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '' at line 1
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:124:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 19:37:24 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'userId' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:124:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 19:39:07 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'userId' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:124:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 19:39:09 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'userId' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:124:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 20:24:24 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:111:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Mon, 05 Dec 2022 20:24:35 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:111:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Tue, 06 Dec 2022 12:20:45 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:111:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Tue, 06 Dec 2022 12:20:52 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'field list'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:111:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Tue, 06 Dec 2022 12:20:57 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:124:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Wed, 07 Dec 2022 07:47:01 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:49:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:14:53)
    at fulfilled (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Wed, 07 Dec 2022 07:52:10 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'user' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:49:35)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:14:53)
    at fulfilled (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Thu, 08 Dec 2022 18:13:01 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:133:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Thu, 08 Dec 2022 18:13:07 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:133:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 11 Dec 2022 07:27:51 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:133:33)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
----------------------------------------------------------------------------------------------------
Sun, 11 Dec 2022 07:29:14 GMT
catchAll error
Stack: TypeError: Cannot convert undefined or null to object
    at Object.getNewToken (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\cyber.ts:14:5)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:56:25)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:14:53)
    at fulfilled (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Sun, 11 Dec 2022 07:39:10 GMT
catchAll error
Stack: Error: Function not implemented.
    at uuid (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:172:11)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:49:30)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.addVacation (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:81:12)
    at C:\Users\klode\Desktop\project-3\Backend\src\6-controllers\vacations-controller.ts:56:52
    at step (C:\Users\klode\Desktop\project-3\Backend\src\6-controllers\vacations-controller.ts:33:23)
----------------------------------------------------------------------------------------------------
Sun, 11 Dec 2022 07:39:25 GMT
catchAll error
Stack: Error: Function not implemented.
    at uuid (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:172:11)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:49:30)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.addVacation (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:81:12)
    at C:\Users\klode\Desktop\project-3\Backend\src\6-controllers\vacations-controller.ts:56:52
    at step (C:\Users\klode\Desktop\project-3\Backend\src\6-controllers\vacations-controller.ts:33:23)
----------------------------------------------------------------------------------------------------
Sun, 11 Dec 2022 15:39:46 GMT
catchAll error
Stack: Error: ER_BAD_NULL_ERROR: Column 'followersCount' cannot be null
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:43:38)
    at step (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:33:23)
    at Object.next (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:14:53)
    at fulfilled (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:5:58)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Mon, 12 Dec 2022 17:06:11 GMT
catchAll error
Stack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:60:29)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
Mon, 12 Dec 2022 17:06:28 GMT
catchAll error
Stack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:60:29)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
Tue, 13 Dec 2022 20:02:47 GMT
catchAll error
Stack: Error: ER_BAD_FIELD_ERROR: Unknown column 'NaN' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:129:33)
    at Generator.next (<anonymous>)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.getVacationsForUser (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:109:12)
----------------------------------------------------------------------------------------------------
Thu, 15 Dec 2022 13:22:52 GMT
catchAll error
Stack: Error: ER_BAD_NULL_ERROR: Column 'imageName' cannot be null
    at Query.Sequence._packetToError (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:526:10)
    at Socket.emit (node:events:520:28)
    at Socket.emit (node:domain:475:12)
    --------------------
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:199:23)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:43:38)
    at Generator.next (<anonymous>)
    at C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:4:12)
    at Object.addVacation (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\vacations-logic.ts:36:12)
----------------------------------------------------------------------------------------------------
Thu, 15 Dec 2022 14:04:44 GMT
catchAll error
Stack: TypeError: Cannot convert undefined or null to object
    at Object.getNewToken (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\cyber.ts:14:5)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:34:25)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Thu, 15 Dec 2022 14:11:02 GMT
catchAll error
Stack: TypeError: Cannot convert undefined or null to object
    at Object.getNewToken (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\cyber.ts:14:5)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:36:25)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:5:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
----------------------------------------------------------------------------------------------------
Mon, 16 Jan 2023 12:36:10 GMT
catchAll error
Stack: Error: connect ECONNREFUSED 127.0.0.1:3306
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1157:16)
    --------------------
    at Protocol._enqueue (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:144:48)
    at Protocol.handshake (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\protocol\Protocol.js:51:23)
    at PoolConnection.connect (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Connection.js:116:18)
    at Pool.getConnection (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:48:16)
    at Pool.query (C:\Users\klode\Desktop\project-3\Backend\node_modules\mysql\lib\Pool.js:202:8)
    at C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:14:20
    at new Promise (<anonymous>)
    at Object.execute (C:\Users\klode\Desktop\project-3\Backend\src\2-utils\dal.ts:13:12)
    at Object.<anonymous> (C:\Users\klode\Desktop\project-3\Backend\src\5-logic\auth-logic.ts:55:29)
    at Generator.next (<anonymous>)
----------------------------------------------------------------------------------------------------
